package io.acelance.graph.dsl.persistence.jdbc;

import com.fasterxml.jackson.databind.ObjectMapper;
import io.acelance.graph.dsl.persistence.support.AbstractJdbcGraphDefinitionRepository;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 * 通用 JDBC 持久化实现（MySQL / PostgreSQL / Oracle 等）。
 */
public class JdbcGraphDefinitionRepository extends AbstractJdbcGraphDefinitionRepository {

    public JdbcGraphDefinitionRepository(JdbcTemplate jdbcTemplate, ObjectMapper objectMapper, String tablePrefix) {
        super(jdbcTemplate, objectMapper, tablePrefix);
    }

    @Override
    protected void initSchema() {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS %s (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    graph_id VARCHAR(128) NOT NULL,
                    version VARCHAR(64) NOT NULL,
                    display_name VARCHAR(256),
                    description CLOB,
                    content_json CLOB NOT NULL,
                    created_at TIMESTAMP NOT NULL
                )
                """.formatted(defTable()));
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS %s (
                    graph_id VARCHAR(128) PRIMARY KEY,
                    version VARCHAR(64) NOT NULL,
                    enabled_at TIMESTAMP NOT NULL
                )
                """.formatted(enabledTable()));
    }
}
